version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: robert
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nats:
    image: nats:2.10
    container_name: nats-server
#    ports:
#      - "5222:4222"

  app:
    build: .
    depends_on:
      - postgres
      - nats
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/mydb
      - DB_USER=robert
      - DB_PASS=12345678
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata:
